name: Terragrunt Workspace Deploy
description: Helps with terragrunt workspace deployments
author: https://github.com/fatzebra
requirements: 
  - terragrunt
  - terraform
  - jq
  - sops
configuration:
  properties:
    module_dir:
      description: The path to the modules that you want to apply
      type: string

    allowed_modules:
      description: A list of modules that can be used by this plugin
      type: array

    data_modules:
      description: Modules that are run with refresh at the start of each command. Used to get the state from modules with only data components
      type: array

    terragrunt_args:
      description: Extra arguments to add to terragrunt commands
      type: array

    debug_pipeline_output:
      description: A file path to output the pipeline to for testing
      type: string

    plan_encryption_kms_key_arn:
      description: The arn of a kms key to encrypt the plan content when passing between steps
      type: string

    fail_on_no_modules:
      description: Should the pipeline step if no modules are found for deploy
      type: boolean
      default: true

  required: 
    - module_dir
  additionalProperties: false
